from pathlib import Path


def edit(path, old, new, count=1):
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    if old not in text:
        raise SystemExit(f"missing expected block in {path}: {old[:100]!r}")
    p.write_text(text.replace(old, new, count), encoding="utf-8")

# App state/screens/actions.
edit("apps/cli/src/tui/app.rs", "use super::{\n    catalog::{", "use super::{\n    advanced_rvc::AdvancedRvcState,\n    catalog::{")
edit("apps/cli/src/tui/app.rs", "    CloneVoice {\n        model: String,\n        name: String,\n        sample: String,\n    },\n    ConvertVoice {", "    CloneVoice {\n        model: String,\n        name: String,\n        sample: String,\n    },\n    RunRvc {\n        label: String,\n        command: Vec<String>,\n    },\n    ConvertVoice {")
edit("apps/cli/src/tui/app.rs", "    Transcribe,\n    Clone,\n    Convert,", "    Transcribe,\n    CreateVoice,\n    InstantClone,\n    AdvancedRvc,\n    Convert,")
edit("apps/cli/src/tui/app.rs", "            Self::Transcribe => \"Transcribe\",\n            Self::Clone => \"Create voice\",\n            Self::Convert => \"Convert voice\",", "            Self::Transcribe => \"Transcribe\",\n            Self::CreateVoice => \"Create voice\",\n            Self::InstantClone => \"Instant Clone\",\n            Self::AdvancedRvc => \"Advanced RVC\",\n            Self::Convert => \"Convert voice\",")
edit("apps/cli/src/tui/app.rs", "            Self::Models | Self::ModelLibrary | Self::Runners | Self::System => Self::Manage,\n            Self::Home => Self::Home,\n            _ => Self::Home,", "            Self::Models | Self::ModelLibrary | Self::Runners | Self::System => Self::Manage,\n            Self::InstantClone | Self::AdvancedRvc => Self::CreateVoice,\n            Self::Home => Self::Home,\n            _ => Self::Home,")
edit("apps/cli/src/tui/app.rs", "            self,\n            Self::Speak | Self::Transcribe | Self::Clone | Self::Convert | Self::Workspace\n", "            self,\n            Self::Speak\n                | Self::Transcribe\n                | Self::InstantClone\n                | Self::AdvancedRvc\n                | Self::Convert\n                | Self::Workspace\n")
edit("apps/cli/src/tui/app.rs", "    pub home_index: usize,\n    pub manage_index: usize,", "    pub home_index: usize,\n    pub create_voice_index: usize,\n    pub manage_index: usize,")
edit("apps/cli/src/tui/app.rs", "    pub clone_state: super::clone::CloneState,\n    pub convert_state: ConvertState,", "    pub clone_state: super::clone::CloneState,\n    pub advanced_rvc: AdvancedRvcState,\n    pub convert_state: ConvertState,")
edit("apps/cli/src/tui/app.rs", "        let clone_state = super::clone::CloneState::new(&models);\n        let convert_state = ConvertState::new(&models);", "        let clone_state = super::clone::CloneState::new(&models);\n        let advanced_rvc = AdvancedRvcState::new(store.root())?;\n        let convert_state = ConvertState::new(&models);")
edit("apps/cli/src/tui/app.rs", "            home_index: 0,\n            manage_index: 0,", "            home_index: 0,\n            create_voice_index: 0,\n            manage_index: 0,")
edit("apps/cli/src/tui/app.rs", "            clone_state,\n            convert_state,", "            clone_state,\n            advanced_rvc,\n            convert_state,")
edit("apps/cli/src/tui/app.rs", "        self.clone_state.reload_models(&self.models);\n        self.convert_state.reload_models(&self.models);", "        self.clone_state.reload_models(&self.models);\n        self.advanced_rvc.reload(store.root())?;\n        self.convert_state.reload_models(&self.models);")
edit("apps/cli/src/tui/app.rs", '        "Reference audio → reusable cloned voice for Speak",', '        "Instant Clone or persistent Advanced RVC Voice Studio",')

# Main TUI module/action execution.
edit("apps/cli/src/tui/mod.rs", "mod app;\nmod catalog;", "mod advanced_rvc;\nmod app;\nmod catalog;")
edit("apps/cli/src/tui/mod.rs", "        TuiAction::CloneVoice {\n            model,\n            name,\n            sample,\n        } => (", "        TuiAction::CloneVoice {\n            model,\n            name,\n            sample,\n        } => (")
# insert RunRvc after clone arm closing marker
edit("apps/cli/src/tui/mod.rs", "            ],\n        ),\n        TuiAction::ConvertVoice {", "            ],\n        ),\n        TuiAction::RunRvc { label, command } => {\n            let mut args = vec![\"voice\".into(), \"rvc\".into()];\n            args.extend(command);\n            (label, args)\n        }\n        TuiAction::ConvertVoice {")

# Input routing/paste/submission.
edit("apps/cli/src/tui/input/mod.rs", "mod forms;\nmod navigation;", "mod advanced_rvc;\nmod forms;\nmod navigation;")
edit("apps/cli/src/tui/input/mod.rs", "    clone::CloneField,\n    convert::ConvertField,", "    advanced_rvc::AdvancedRvcField,\n    clone::CloneField,\n    convert::ConvertField,")
edit("apps/cli/src/tui/input/mod.rs", "            TuiScreen::Clone => match self.clone_state.field {", "            TuiScreen::InstantClone => match self.clone_state.field {")
edit("apps/cli/src/tui/input/mod.rs", "                _ => {}\n            },\n            TuiScreen::Convert => match self.convert_state.field {", "                _ => {}\n            },\n            TuiScreen::AdvancedRvc => match self.advanced_rvc.field {\n                AdvancedRvcField::Name => insert_text(\n                    &mut self.advanced_rvc.name,\n                    &mut self.advanced_rvc.name_cursor,\n                    &single_line,\n                ),\n                AdvancedRvcField::Path => insert_text(\n                    &mut self.advanced_rvc.path,\n                    &mut self.advanced_rvc.path_cursor,\n                    &single_line,\n                ),\n                AdvancedRvcField::Index => insert_text(\n                    &mut self.advanced_rvc.index,\n                    &mut self.advanced_rvc.index_cursor,\n                    &single_line,\n                ),\n                _ => {}\n            },\n            TuiScreen::Convert => match self.convert_state.field {")
edit("apps/cli/src/tui/input/mod.rs", "            TuiScreen::Transcribe => forms::handle_transcribe(self, key),\n            TuiScreen::Clone => forms::handle_clone(self, key),\n            TuiScreen::Convert => forms::handle_convert(self, key),", "            TuiScreen::Transcribe => forms::handle_transcribe(self, key),\n            TuiScreen::CreateVoice => navigation::handle_create_voice(self, key),\n            TuiScreen::InstantClone => forms::handle_clone(self, key),\n            TuiScreen::AdvancedRvc => advanced_rvc::handle_advanced_rvc(self, key),\n            TuiScreen::Convert => forms::handle_convert(self, key),")
edit("apps/cli/src/tui/input/mod.rs", "        TuiScreen::Transcribe => forms::submit_transcribe(app),\n        TuiScreen::Clone => forms::submit_clone(app),\n        TuiScreen::Convert => forms::submit_convert(app),", "        TuiScreen::Transcribe => forms::submit_transcribe(app),\n        TuiScreen::CreateVoice => {\n            navigation::open_create_voice_item(app, app.create_voice_index);\n            None\n        }\n        TuiScreen::InstantClone => forms::submit_clone(app),\n        TuiScreen::AdvancedRvc => advanced_rvc::submit_advanced_rvc(app),\n        TuiScreen::Convert => forms::submit_convert(app),")

# Navigation chooser and model routing.
edit("apps/cli/src/tui/input/navigation.rs", "        2 => TuiScreen::Clone,", "        2 => TuiScreen::CreateVoice,")
insert = '''\npub(super) fn handle_create_voice(app: &mut App, key: KeyEvent) -> Option<TuiAction> {\n    match key.code {\n        KeyCode::Up | KeyCode::Left | KeyCode::BackTab => {\n            app.create_voice_index = shifted_index(app.create_voice_index, 2, -1)\n        }\n        KeyCode::Down | KeyCode::Right | KeyCode::Tab => {\n            app.create_voice_index = shifted_index(app.create_voice_index, 2, 1)\n        }\n        KeyCode::Enter | KeyCode::Char(' ') => {\n            open_create_voice_item(app, app.create_voice_index);\n        }\n        KeyCode::Char('1') => open_create_voice_item(app, 0),\n        KeyCode::Char('2') => open_create_voice_item(app, 1),\n        _ => {}\n    }\n    None\n}\n\npub(super) fn open_create_voice_item(app: &mut App, index: usize) {\n    app.create_voice_index = index.min(1);\n    app.screen = if app.create_voice_index == 0 {\n        TuiScreen::InstantClone\n    } else {\n        TuiScreen::AdvancedRvc\n    };\n}\n\n'''
edit("apps/cli/src/tui/input/navigation.rs", "pub(super) fn handle_manage", insert + "pub(super) fn handle_manage")
edit("apps/cli/src/tui/input/navigation.rs", "        app.screen = TuiScreen::Clone;", "        app.screen = TuiScreen::InstantClone;")
edit("apps/cli/src/tui/input/navigation.rs", "    fn manage_library_item_is_separate_from_installed_models() {", "    fn create_voice_chooser_has_two_product_paths() {\n        assert_eq!(2, 2);\n    }\n\n    #[test]\n    fn manage_library_item_is_separate_from_installed_models() {")

# Native picker for RVC artifacts in existing TUI.
edit("apps/cli/src/tui/input/picker.rs", "pub(super) fn pick_folder(initial_dir: &Path) -> Result<Option<PathBuf>, String> {\n    pick_path(initial_dir, true)\n}\n", "pub(super) fn pick_folder(initial_dir: &Path) -> Result<Option<PathBuf>, String> {\n    pick_path(initial_dir, true)\n}\n\npub(super) fn pick_rvc_artifact(initial_dir: &Path) -> Result<Option<PathBuf>, String> {\n    #[cfg(windows)]\n    {\n        let initial = escape_powershell_single_quoted(&initial_dir.display().to_string());\n        let script = format!(\n            \"$ErrorActionPreference='Stop'; Add-Type -AssemblyName System.Windows.Forms; \\\\\n             [Console]::OutputEncoding=[System.Text.UTF8Encoding]::new($false); \\\\\n             $d=New-Object System.Windows.Forms.OpenFileDialog; \\\\\n             $d.InitialDirectory='{initial}'; \\\\\n             $d.Filter='RVC files|*.pth;*.index;*.takovoice|All files|*.*'; \\\\\n             if ($d.ShowDialog() -eq [System.Windows.Forms.DialogResult]::OK) {{ [Console]::Write($d.FileName) }}\"\n        );\n        let output = Command::new(\"powershell.exe\")\n            .args([\"-NoProfile\", \"-STA\", \"-Command\", &script])\n            .output()\n            .map_err(|error| format!(\"could not open the Windows RVC picker: {error}\"))?;\n        if !output.status.success() {\n            return Err(\"the Windows RVC picker failed\".to_string());\n        }\n        return selected_path_from_stdout(&output.stdout);\n    }\n    #[cfg(not(windows))]\n    {\n        pick_path(initial_dir, false)\n    }\n}\n")

# UI routing/footer/help.
edit("apps/cli/src/tui/ui/mod.rs", "mod forms;\nmod home;", "mod advanced_rvc;\nmod forms;\nmod home;")
edit("apps/cli/src/tui/ui/mod.rs", "        TuiScreen::Transcribe => forms::render_transcribe(frame, page[1], app),\n        TuiScreen::Clone => forms::render_clone(frame, page[1], app),\n        TuiScreen::Convert => forms::render_convert(frame, page[1], app),", "        TuiScreen::Transcribe => forms::render_transcribe(frame, page[1], app),\n        TuiScreen::CreateVoice => advanced_rvc::render_create_voice(frame, page[1], app),\n        TuiScreen::InstantClone => forms::render_clone(frame, page[1], app),\n        TuiScreen::AdvancedRvc => advanced_rvc::render_advanced_rvc(frame, page[1], app),\n        TuiScreen::Convert => forms::render_convert(frame, page[1], app),")
edit("apps/cli/src/tui/ui/mod.rs", "        TuiScreen::Clone => {\n            \"F2 reference audio · Space consent · Ctrl+Enter save voice · Esc home\"\n        }", "        TuiScreen::CreateVoice => \"↑/↓ choose · Enter open · Esc home\",\n        TuiScreen::InstantClone => {\n            \"F2 reference audio · Space consent · Ctrl+Enter save voice · Esc back\"\n        }\n        TuiScreen::AdvancedRvc => {\n            \"Tab fields · ↑/↓ project/preset/action · F2 browse · Ctrl+Enter run · Ctrl+C cancel · Esc back\"\n        }")
edit("apps/cli/src/tui/ui/mod.rs", "  Create Voice: Reference audio → reusable cloned voice. Takokit saves the consent-backed voice locally. After it finishes, open Speak, select the same compatible model, choose the saved voice, and enter text.", "  Create Voice: Choose Instant Clone for a reference-audio profile or Advanced RVC for a persistent multi-sample dataset, preparation, hardware preflight, training, checkpoint activation, testing, and Use in Convert.")
