import { FileAudio, FileText } from "lucide-react";
import { useMemo, useState } from "react";
import type { RouteComponentProps } from "../../app/routes";
import { Badge } from "../../components/ui/Badge";
import { Button } from "../../components/ui/Button";
import { Section } from "../../components/ui/Section";
import { Select } from "../../components/ui/Select";
import { Table, TableRow } from "../../components/ui/Table";
import { installRunner, pullModel, pullRunner, transcribeAudio } from "../../lib/api";

export function TranscribePage({ runtime, onRefresh }: RouteComponentProps) {
  const sttModels = useMemo(() => runtime.models.filter((model) => model.capabilities.includes("stt")), [runtime.models]);
  const [model, setModel] = useState(sttModels.find((item) => item.id === "whisper-base")?.id ?? sttModels[0]?.id ?? "");
  const [filePath, setFilePath] = useState("");
  const [busyAction, setBusyAction] = useState<string | null>(null);
  const [transcript, setTranscript] = useState<string | null>(null);
  const [notice, setNotice] = useState<string | null>(null);
  const selectedModel = sttModels.find((item) => item.id === model) ?? sttModels[0];
  const requiredRunner = selectedModel ? runtime.runners.find((runner) => runner.id === selectedModel.runner) : undefined;
  const apiUnavailable = runtime.server.status !== "online";
  const blocker = apiUnavailable
    ? "Start takokit serve or takokit gui to use the local API."
    : selectedModel?.executable
      ? null
      : selectedModel?.missing.join("; ") || "This STT model is not executable today.";

  async function runAction(label: string, action: () => Promise<void>) {
    setBusyAction(label);
    setNotice(null);
    try {
      await action();
      await onRefresh();
      setNotice("Local runtime state updated.");
    } catch (error) {
      setNotice(error instanceof Error ? error.message : "Takokit API action failed.");
    } finally {
      setBusyAction(null);
    }
  }

  async function runTranscription() {
    setBusyAction("transcribe");
    setNotice(null);
    setTranscript(null);
    try {
      const response = await transcribeAudio({ model: selectedModel?.id, file_path: filePath });
      setTranscript(response.text);
      setNotice(`Transcript generated by ${response.model}.`);
    } catch (error) {
      setNotice(error instanceof Error ? error.message : "Transcription failed.");
    } finally {
      setBusyAction(null);
    }
  }

  return (
    <section className="page">
      <header className="page__header">
        <h1>Transcribe</h1>
        <p>Run local STT through the same Whisper path used by the CLI and API.</p>
      </header>

      <Section title="Audio input" description="Use a local file path that the Takokit daemon can read.">
        <div className="upload-zone">
          <div className="upload-zone__icon">
            <FileAudio size={24} aria-hidden="true" />
          </div>
          <div className="field">
            <label htmlFor="transcribe-path">Audio file path</label>
            <input
              id="transcribe-path"
              className="search-input"
              value={filePath}
              onChange={(event) => setFilePath(event.target.value)}
              placeholder="C:\\path\\to\\sample.wav"
            />
            <small>Takokit does not upload to a cloud service; the local daemon reads this path.</small>
          </div>
          <Button
            type="button"
            variant="primary"
            disabled={!selectedModel?.executable || !filePath.trim() || apiUnavailable}
            loading={busyAction === "transcribe"}
            onClick={() => void runTranscription()}
          >
            <FileText size={16} /> Transcribe
          </Button>
        </div>
      </Section>

      <Section title="Prerequisites">
        <div className="form-grid">
          <Select
            label="Model"
            value={model}
            onChange={(event) => setModel(event.target.value)}
            hint={`${selectedModel?.family ?? "stt"} - ${selectedModel?.lifecycleState ?? "unknown"}`}
            options={sttModels.map((item) => ({ value: item.id, label: item.name }))}
          />
          <div className="generation-actions">
            <div className="generation-actions__meta">
              <strong>{selectedModel?.name ?? "No STT model"}</strong>
              <span>{blocker ?? "Ready for a local transcription request."}</span>
            </div>
            <span className="badge-list">
              <Badge tone={selectedModel?.status === "installed" ? "success" : "warning"}>{selectedModel?.status ?? "missing"}</Badge>
              <Badge tone={selectedModel?.runnerRuntimeState === "ready" ? "success" : "warning"}>runner {selectedModel?.runnerRuntimeState ?? "missing"}</Badge>
              <Badge tone={selectedModel?.executable ? "success" : "warning"}>{selectedModel?.executable ? "executable" : "blocked"}</Badge>
            </span>
            <span className="action-cluster">
              <Button
                type="button"
                variant="ghost"
                disabled={apiUnavailable || !selectedModel || selectedModel.status === "installed"}
                loading={busyAction === "pull-model"}
                onClick={() => selectedModel && runAction("pull-model", () => pullModel(selectedModel.id).then(() => undefined))}
              >
                Pull model
              </Button>
              <Button
                type="button"
                variant="ghost"
                disabled={apiUnavailable || !requiredRunner || requiredRunner.installed}
                loading={busyAction === "pull-runner"}
                onClick={() => requiredRunner && runAction("pull-runner", () => pullRunner(requiredRunner.id).then(() => undefined))}
              >
                Pull runner
              </Button>
              <Button
                type="button"
                variant="ghost"
                disabled={apiUnavailable || !requiredRunner?.installed || requiredRunner.install_state === "ready"}
                loading={busyAction === "install-runner"}
                onClick={() => requiredRunner && runAction("install-runner", () => installRunner(requiredRunner.id).then(() => undefined))}
              >
                Install runner
              </Button>
            </span>
            <span className="details-panel__runner">Next: {selectedModel?.nextCommand ?? "takokit models"}</span>
          </div>
        </div>
        {notice && <p className="notice-line">{notice}</p>}
      </Section>

      <Section title="Transcript">
        <pre className="logs-panel">{transcript ?? "No transcript yet."}</pre>
      </Section>

      <Section title="STT models">
        <Table columns={["Model", "Runner", "Lifecycle", "Executable", "Missing"]} ariaLabel="Speech to text models">
          {sttModels.map((item) => (
            <TableRow key={item.id}>
              <strong>{item.name}</strong>
              <span>{item.runner}</span>
              <Badge tone={item.executable ? "success" : "neutral"}>{item.lifecycleState}</Badge>
              <Badge tone={item.executable ? "success" : "warning"}>{item.executable ? "yes" : "no"}</Badge>
              <span>{item.missing.join("; ") || "-"}</span>
            </TableRow>
          ))}
        </Table>
      </Section>
    </section>
  );
}
